export const packages = {
    dev: [
        '@testing-library/jest-dom',
        '@testing-library/react',
        '@types/jest',
        '@types/node',
        'eslint',
        'eslint-config-prettier',
        'eslint-plugin-prettier',
        'eslint-plugin-react',
        'eslint-plugin-react-hooks',
        'eslint-plugin-simple-import-sort',
        'globals',
        'husky',
        'lint-staged',
        'npm-run-all',
        'prettier',
        'typescript',
        'typescript-eslint',
    ],
}
